version: '3'
services:
  yolov8_fastapi:
    build: .
    restart: "always"
    volumes:
    - ./:/app
    working_dir: /app
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 443 --ssl-keyfile /etc/letsencrypt/live/koabiotech.com/privkey.pem --ssl-certfile /etc/letsencrypt/live/koabiotech.com/fullchain.pem
